apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: api-gateway
  namespace: applications

  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: order-fulfillment-platform

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: api-gateway-secrets
    creationPolicy: Owner

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: eks-v2-dev/api-gateway/jwt-secret
