apiVersion: v1
kind: ServiceAccount

metadata:
  name: api-gateway
  namespace: applications

  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: order-fulfillment-platform