apiVersion: v1
kind: ServiceAccount

metadata:
  name: scheduler
  namespace: applications

  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: order-fulfillment-platform