apiVersion: v1
kind: Service

metadata:
  name: shipping-service
  namespace: applications

  labels:
    app.kubernetes.io/name: shipping-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: order-fulfillment-platform

spec:
  type: ClusterIP

  selector:
    app: shipping-service

  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP