apiVersion: v1
kind: ServiceAccount

metadata:
  name: worker
  namespace: applications

  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: background-worker
    app.kubernetes.io/part-of: order-fulfillment-platform

  annotations:
    eks.amazonaws.com/role-arn: REPLACE_AFTER_TERRAFORM_APPLY