apiVersion: v1
kind: ServiceAccount

metadata:
  name: order-service
  namespace: applications

  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: order-fulfillment-platform