apiVersion: keda.sh/v1alpha1
kind: ScaledObject

metadata:
  name: worker
  namespace: applications

  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: order-fulfillment-platform

spec:
  scaleTargetRef:
    name: worker

  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10

  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 120

  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-aws
      metadata:
        queueURL: https://sqs.eu-west-2.amazonaws.com/283434716298/eks-v2-dev-order-events
        queueLength: "5"
        awsRegion: eu-west-2
