apiVersion: v1
kind: ConfigMap

metadata:
  name: redis-config
  namespace: data

  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: order-fulfillment-platform

data:
  redis.conf: |
    appendonly yes
    save 60 1000
    maxmemory-policy allkeys-lru