apiVersion: v1
kind: ServiceAccount

metadata:
  name: redis
  namespace: data

  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: order-fulfillment-platform

automountServiceAccountToken: false