apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-data-allow.yaml
  - pdb.yaml
