apiVersion: v1
kind: Namespace
metadata:
  name: applications
  labels:
    app.kubernetes.io/part-of: order-fulfillment-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: order-fulfillment-platform
    kubernetes.io/metadata.name: data
