apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-config
  namespace: data

  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: order-fulfillment-platform

data:
  POSTGRES_DB: orders

  PGDATA: /var/lib/postgresql/data/pgdata

  TZ: UTC
  