apiVersion: v1
kind: ServiceAccount

metadata:
  name: notification-service
  namespace: applications

  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: order-fulfillment-platform

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::283434716298:role/eks-v2-dev-notification-service
