apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: payment-service
  namespace: applications

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: payment-service-secrets
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: eks-v2-dev/database/url