name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/infra-ci.yml"

  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/infra-ci.yml"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
              
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Show TFLint version
        run: tflint --version

      - name: Initialise TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint
              
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          framework: terraform
          quiet: true